global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

clusterGroup:
  name: region-two
  isHubCluster: false

  namespaces:
  - cockroachdb

  subscriptions:

  projects:
  - cockroachdb

  applications:
  - name: cockroachdb
    namespace: cockroachdb
    project: cockroachdb
    path: charts/all/cockroachdb
    syncPolicy:
      automated: {}
      retry:
        limit: 50
    overrides:
    - name: provider
      value: az
    - name: replicas
      value: 3
    - name: vault.clusterSecretStoreName
      value: vault-backend
    - name: resources.requests.cpu
      value: "1"
    - name: resources.requests.memory
      value: "2Gi"
    - name: resources.limits.cpu
      value: "1"
    - name: resources.limits.memory
      value: "2Gi"
    - name: region
      value: eastus
    - name: zone
      value: eastus-1
    - name: clusters.0
      value: region-one
    - name: clusters.1
      value: region-two
    - name: clusters.2
      value: region-three
    - name: clusterName
      value: region-two

  imperative:
    # NOTE: We *must* use lists and not hashes. As hashes lose ordering once parsed by helm
    jobs:
    - name: get-hub
      playbook: ansible/playbooks/on-regional-get-hub-ca.yml
      timeout: 123

#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#    pipelines:
#      name: pipelines
#      namespace: production
#      project: datacenter
#      path: applications/pipeline
#      repoURL: https://github.com/you/applications.git
#      targetRevision: stable
#      overrides:
#      - name: myparam
#        value: myparam
#
#    pipelines_staging:
#    - name: pipelines
#      namespace: staging
#      project: datacenter
#      path: applications/pipeline
#      repoURL: https://github.com/you/applications.git
#      targetRevision: main
#
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#    vendor-app:
#      name: vendor-app
#      namespace: default
#      project: vendor
#      path: path/to/myapp
#      repoURL: https://github.com/vendor/applications.git
#      targetRevision: main

#  managedSites:
#    factory:
#      name: factory
#      # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
#      targetRevision: main
#      path: applications/factory
#      helmOverrides:
#      - name: site.isHubCluster
#        value: false
#      clusterSelector:
#        matchExpressions:
#        - key: vendor
#          operator: In
#          values:
#            - OpenShift
