---
global:
  pattern: cockroachdb-pattern
  vault:
    secretStoreName: vault-backend

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

main:
  clusterGroupName: hub
